# The URL the site will be built for
base_url = "https://ertibus.gitlab.io/"

# Feeds
title = "Ertibus Blog"
description = "Ertibus blog about programming and stuff"
default_language = "en"
generate_feed = true
feed_filename = "rss.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

build_search_index = true


taxonomies = [
    { name = "tags", feed = true, paginate_by = 8 },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "1337"
render_emoji = true

[extra]
